### ISSUE TITLE
How do I build and run this?

### ISSUE THREAD

**Issue by PhilAndrew** [ggrandes/bouncer#15]
mvn compile package 

Is that right?

but I run it and it says cannot find the class file.

I guess my question is how to get all the jars into the lib directory.

**Comment by ggrandes** [comment]
This is the script:

    git clone https://github.com/ggrandes/bouncer
    cd bouncer
    mvn package

This generate ./target/bouncer-2.x.x-bin.zip; nothing more is needed...
